#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config ignore_ewmh_focus    false


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a Geany desktop='^4' follow=on
bspc rule -a Thunar desktop='^3' follow=on 





# wallpaper
${HOME}/.fehbg


########THEME-BSPWM########################################
#Border
#bspc config focused_border_color       "#973e95"
#;bspc config focused_border_color       "#6c71c4"
#bspc config normal_border_color        "#24244f"
#bspc config active_border_color        "#7b68ee"

##Boder 2
# bspc config normal_border_color "#070C1E"
 #bspc config active_border_color "#F0C674"
 #bspc config focused_border_color "#F0C674"
 #bspc config presel_border_color "#2E64FE"
 #bspc config urgent_border_color "#2E64FE"
 #bspc config presel_feedback_color "#2E64FE"

bspc config normal_border_color "#44475a"
bspc config active_border_color "#A3BE8C"
bspc config focused_border_color "#A3BE8C"
bspc config presel_feedback_color "#6272a4"






#${HOME}/.config/polybar/launch.sh
#~/.config/polybar/launch.sh
xfce4-power-manager &
picom -b &
polybar -r &
network-manager-applet &
